services:
  # Backend + frontend juntos
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monorepo-app
    ports:
      - "${APP_PORT:-3100}:3100"
    environment:
      # App settings
      APP_PORT: ${APP_PORT:-3100}
      TENANT_ID: ${TENANT_ID}

      # ArangoDB
      ARANGODB_URL: ${ARANGODB_URL}
      ARANGODB_DATABASE: ${ARANGODB_DATABASE}
      ARANGODB_USERNAME: ${ARANGODB_USERNAME}
      ARANGODB_PASSWORD: ${ARANGODB_PASSWORD}

      # Gemini API
      GEMINI_API_KEY: ${GEMINI_API_KEY}

      # Postgres
      DATABASE_URL: postgresql://postgres:postgres@db:5432/memora

      # Storage
      STORAGE_TYPE: ${STORAGE_TYPE}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_ENDPOINT: ${AWS_ENDPOINT}
      AWS_PUBLIC_BUCKET_BASE_URL: ${AWS_PUBLIC_BUCKET_BASE_URL}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_FORCE_PATH_STYLE: ${AWS_FORCE_PATH_STYLE}
    depends_on:
      - arangodb
      - redis
      - db
      - minio
    restart: unless-stopped

  # ArangoDB
  arangodb:
    image: arangodb:latest
    container_name: arangodb
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGODB_PASSWORD}
    ports:
      - "8529:8529"
    volumes:
      - arangodb-data:/var/lib/arangodb3
    restart: unless-stopped

  # Redis
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  # Postgres
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: memora
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  # MinIO (S3)
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Console
    volumes:
      - minio-data:/data
    restart: unless-stopped

volumes:
  arangodb-data:
  redis-data:
  postgres-data:
  minio-data:
