import { MigrationInterface, QueryRunner } from "typeorm";

export class Initial1764268028888 implements MigrationInterface {
    name = 'Initial1764268028888'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "provider" character varying(255) NOT NULL, "provider_account_id" character varying(255) NOT NULL, "user_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_06f1ce45cbf093e57b824205565" UNIQUE ("provider", "provider_account_id"), CONSTRAINT "PK_5a7a02c20412299d198e097a8fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."roles_scope_enum" AS ENUM('TENANT', 'GLOBAL')`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying NOT NULL, "name" character varying NOT NULL, "permissions" integer NOT NULL, "scope" "public"."roles_scope_enum" NOT NULL DEFAULT 'TENANT', "tenant_id" uuid, "created_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "roles_key_scope_tenant_id_unique" UNIQUE ("key", "scope", "tenant_id"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."messages_message_role_enum" AS ENUM('user', 'assistant', 'system')`);
        await queryRunner.query(`CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "message_role" "public"."messages_message_role_enum" NOT NULL, "content" text NOT NULL, "chat_id" uuid NOT NULL, "knowledge_id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "chats" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(50) NOT NULL, "knowledge_id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0117647b3c4a4e5ff198aeb6206" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."llms_type_enum" AS ENUM('EMBEDDING', 'TEXT')`);
        await queryRunner.query(`CREATE TABLE "llms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "default" boolean NOT NULL DEFAULT false, "key" character varying(255) NOT NULL, "name" character varying(255) NOT NULL, "model" character varying(255) NOT NULL, "config" jsonb NOT NULL DEFAULT '{}', "type" "public"."llms_type_enum" NOT NULL, "tenant_id" character varying(36) NOT NULL, "creator_id" character varying(36), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "llms_default_tenant_type_unique" UNIQUE ("default", "tenant_id", "type"), CONSTRAINT "llms_name_tenant_unique" UNIQUE ("name", "tenant_id"), CONSTRAINT "PK_2ec003633cdb2e9b49777105b3f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "knowledge_llms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "default" boolean NOT NULL DEFAULT false, "knowledge_id" uuid NOT NULL, "llm_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "knowledge_llm_unique" UNIQUE ("knowledge_id", "llm_id"), CONSTRAINT "PK_e100f76dd9002009335b064a6e9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "knowledge_llm_llm_idx" ON "knowledge_llms" ("llm_id") `);
        await queryRunner.query(`CREATE INDEX "knowledge_llm_knowledge_idx" ON "knowledge_llms" ("knowledge_id") `);
        await queryRunner.query(`CREATE TYPE "public"."knowledge_status_enum" AS ENUM('DELETING', 'DELETE_ERROR', 'OK')`);
        await queryRunner.query(`CREATE TABLE "knowledge" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying(255) NOT NULL, "title" character varying(255) NOT NULL, "description" text, "status" "public"."knowledge_status_enum" NOT NULL DEFAULT 'OK', "delete_error" text, "file_count" integer NOT NULL DEFAULT '0', "storage" bigint NOT NULL DEFAULT '0', "tenant_id" character varying(36) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "knowledge_tenant_slug_unique" UNIQUE ("tenant_id", "slug"), CONSTRAINT "PK_4159ba98b65a20a8d1f257bc514" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "knowledge_tenant_idx" ON "knowledge" ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "folders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "knowledge_id" uuid NOT NULL, "name" character varying(100) NOT NULL, "root" boolean, "parent_id" uuid, "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8578bd31b0e7f6d6c2480dbbca8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."sources_source_type_enum" AS ENUM('TEXT', 'DOC', 'LINK', 'VIDEO', 'AUDIO', 'IMAGE')`);
        await queryRunner.query(`CREATE TYPE "public"."sources_index_status_enum" AS ENUM('PENDING', 'INDEXING', 'INDEXED', 'ERROR')`);
        await queryRunner.query(`CREATE TABLE "sources" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" text NOT NULL, "path" text NOT NULL, "name" character varying(255) NOT NULL, "description" text, "original_name" character varying(255), "metadata" jsonb NOT NULL, "source_type" "public"."sources_source_type_enum" NOT NULL, "index_status" "public"."sources_index_status_enum" NOT NULL, "index_error" text, "memory_id" uuid, "knowledge_id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "folder_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_85523beafe5a2a6b90b02096443" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "sources_index_status_idx" ON "sources" ("index_status") `);
        await queryRunner.query(`CREATE INDEX "sources_key_idx" ON "sources" ("key") `);
        await queryRunner.query(`CREATE INDEX "sources_memory_idx" ON "sources" ("memory_id") `);
        await queryRunner.query(`CREATE TABLE "tenants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "background_image" character varying, "disabled_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_53be67a04681c66b87ee27c9321" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" character varying NOT NULL, "link" character varying, "read" boolean NOT NULL DEFAULT false, "tenant_id" uuid NOT NULL, "created_by_id" uuid, "destination_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "read_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "owner" boolean NOT NULL DEFAULT false, "user_id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "role_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_28b53062261b996d9c99fa12404" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a554f50aa421c895a5d6df6fc7" ON "members" ("tenant_id", "user_id") `);
        await queryRunner.query(`CREATE TABLE "invites" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "email" character varying NOT NULL, "roleId" character varying NOT NULL, "userId" character varying, "creator_id" uuid NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenant_id" uuid, "role_id" uuid, "user_id" uuid, CONSTRAINT "invites_tenant_email_unique" UNIQUE ("tenantId", "email"), CONSTRAINT "PK_aa52e96b44a714372f4dd31a0af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "email" text NOT NULL, "password" text, "email_verified" TIMESTAMP WITH TIME ZONE, "image" text, "role_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."verification_tokens_type_enum" AS ENUM('ACTIVE_ACCOUNT', 'RESET_PASSWORD')`);
        await queryRunner.query(`CREATE TABLE "verification_tokens" ("token" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."verification_tokens_type_enum" NOT NULL, "expires" TIMESTAMP WITH TIME ZONE NOT NULL, "user_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b00b1be0e5a820594d7c07a3dfb" PRIMARY KEY ("token"))`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "FK_3000dad1da61b29953f07476324" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "FK_e59a01f4fe46ebbece575d9a0fc" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "FK_4a39f3095781cdd9d6061afaae5" FOREIGN KEY ("created_by") REFERENCES "members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_7540635fef1922f0b156b9ef74f" FOREIGN KEY ("chat_id") REFERENCES "chats"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_c8c855f76c8a3d10aa3d0c09884" FOREIGN KEY ("knowledge_id") REFERENCES "knowledge"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chats" ADD CONSTRAINT "FK_ba607a517223a0649d07471c004" FOREIGN KEY ("knowledge_id") REFERENCES "knowledge"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "knowledge_llms" ADD CONSTRAINT "FK_aac159fc31d69c0a777bb6e68f0" FOREIGN KEY ("knowledge_id") REFERENCES "knowledge"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "knowledge_llms" ADD CONSTRAINT "FK_6dd2c272fadd0c2c2639f9ddb53" FOREIGN KEY ("llm_id") REFERENCES "llms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "folders" ADD CONSTRAINT "FK_b697ebfd61eef6ffcd13e85dfd9" FOREIGN KEY ("knowledge_id") REFERENCES "knowledge"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "folders" ADD CONSTRAINT "FK_938a930768697b6ece215667d8e" FOREIGN KEY ("parent_id") REFERENCES "folders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sources" ADD CONSTRAINT "FK_9ba789d14dc979a909d2c51aa44" FOREIGN KEY ("knowledge_id") REFERENCES "knowledge"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sources" ADD CONSTRAINT "FK_857e8d6bdd754a2ffb702c40c6a" FOREIGN KEY ("folder_id") REFERENCES "folders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sources" ADD CONSTRAINT "FK_5f5a82b3c01204d3a32632dbdce" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_d93ddd7e1b890535ecafbb334ec" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_8abe9303bccd29799a4d435eb03" FOREIGN KEY ("created_by_id") REFERENCES "members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_ecde827239a7ef36bbcd9bd5aef" FOREIGN KEY ("destination_id") REFERENCES "members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "members" ADD CONSTRAINT "FK_da404b5fd9c390e25338996e2d1" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "members" ADD CONSTRAINT "FK_844f9f34eaefdb094ef9664dc65" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "members" ADD CONSTRAINT "FK_274c5ebb3c595f5a56f1f8fba9a" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invites" ADD CONSTRAINT "FK_a3ad8c552d7c4c5320758376c1b" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invites" ADD CONSTRAINT "FK_8b432fcafe8246529b0476feb59" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invites" ADD CONSTRAINT "FK_188bacba32eb63b759f3578dd5b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invites" ADD CONSTRAINT "FK_76f6a446d903e8bc9b5f418fe4a" FOREIGN KEY ("creator_id") REFERENCES "members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "verification_tokens" ADD CONSTRAINT "FK_31d2079dc4079b80517d31cf4f2" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "verification_tokens" DROP CONSTRAINT "FK_31d2079dc4079b80517d31cf4f2"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "invites" DROP CONSTRAINT "FK_76f6a446d903e8bc9b5f418fe4a"`);
        await queryRunner.query(`ALTER TABLE "invites" DROP CONSTRAINT "FK_188bacba32eb63b759f3578dd5b"`);
        await queryRunner.query(`ALTER TABLE "invites" DROP CONSTRAINT "FK_8b432fcafe8246529b0476feb59"`);
        await queryRunner.query(`ALTER TABLE "invites" DROP CONSTRAINT "FK_a3ad8c552d7c4c5320758376c1b"`);
        await queryRunner.query(`ALTER TABLE "members" DROP CONSTRAINT "FK_274c5ebb3c595f5a56f1f8fba9a"`);
        await queryRunner.query(`ALTER TABLE "members" DROP CONSTRAINT "FK_844f9f34eaefdb094ef9664dc65"`);
        await queryRunner.query(`ALTER TABLE "members" DROP CONSTRAINT "FK_da404b5fd9c390e25338996e2d1"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_ecde827239a7ef36bbcd9bd5aef"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_8abe9303bccd29799a4d435eb03"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_d93ddd7e1b890535ecafbb334ec"`);
        await queryRunner.query(`ALTER TABLE "sources" DROP CONSTRAINT "FK_5f5a82b3c01204d3a32632dbdce"`);
        await queryRunner.query(`ALTER TABLE "sources" DROP CONSTRAINT "FK_857e8d6bdd754a2ffb702c40c6a"`);
        await queryRunner.query(`ALTER TABLE "sources" DROP CONSTRAINT "FK_9ba789d14dc979a909d2c51aa44"`);
        await queryRunner.query(`ALTER TABLE "folders" DROP CONSTRAINT "FK_938a930768697b6ece215667d8e"`);
        await queryRunner.query(`ALTER TABLE "folders" DROP CONSTRAINT "FK_b697ebfd61eef6ffcd13e85dfd9"`);
        await queryRunner.query(`ALTER TABLE "knowledge_llms" DROP CONSTRAINT "FK_6dd2c272fadd0c2c2639f9ddb53"`);
        await queryRunner.query(`ALTER TABLE "knowledge_llms" DROP CONSTRAINT "FK_aac159fc31d69c0a777bb6e68f0"`);
        await queryRunner.query(`ALTER TABLE "chats" DROP CONSTRAINT "FK_ba607a517223a0649d07471c004"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_c8c855f76c8a3d10aa3d0c09884"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_7540635fef1922f0b156b9ef74f"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "FK_4a39f3095781cdd9d6061afaae5"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "FK_e59a01f4fe46ebbece575d9a0fc"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "FK_3000dad1da61b29953f07476324"`);
        await queryRunner.query(`DROP TABLE "verification_tokens"`);
        await queryRunner.query(`DROP TYPE "public"."verification_tokens_type_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "invites"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a554f50aa421c895a5d6df6fc7"`);
        await queryRunner.query(`DROP TABLE "members"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "tenants"`);
        await queryRunner.query(`DROP INDEX "public"."sources_memory_idx"`);
        await queryRunner.query(`DROP INDEX "public"."sources_key_idx"`);
        await queryRunner.query(`DROP INDEX "public"."sources_index_status_idx"`);
        await queryRunner.query(`DROP TABLE "sources"`);
        await queryRunner.query(`DROP TYPE "public"."sources_index_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."sources_source_type_enum"`);
        await queryRunner.query(`DROP TABLE "folders"`);
        await queryRunner.query(`DROP INDEX "public"."knowledge_tenant_idx"`);
        await queryRunner.query(`DROP TABLE "knowledge"`);
        await queryRunner.query(`DROP TYPE "public"."knowledge_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."knowledge_llm_knowledge_idx"`);
        await queryRunner.query(`DROP INDEX "public"."knowledge_llm_llm_idx"`);
        await queryRunner.query(`DROP TABLE "knowledge_llms"`);
        await queryRunner.query(`DROP TABLE "llms"`);
        await queryRunner.query(`DROP TYPE "public"."llms_type_enum"`);
        await queryRunner.query(`DROP TABLE "chats"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP TYPE "public"."messages_message_role_enum"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TYPE "public"."roles_scope_enum"`);
        await queryRunner.query(`DROP TABLE "accounts"`);
    }

}
